apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-hello
  labels:
    app: argocd-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-hello
  template:
    metadata:
      labels:
        app: argocd-hello
        app2: argocd-hello2
    spec:
      containers:
        - name: go-hello-http
          image: "nginx"
          ports:
            - containerPort: 80
