apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-hello
  labels:
    app: argocd-hello
spec:
  replicas: 0
  selector:
    matchLabels:
      app: argocd-hello
  template:
    metadata:
      labels:
        app: argocd-hello
    spec:
      containers:
        - name: go-hello-http
          image: "nginx"
          ports:
            - containerPort: 80
