apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-hello
  template:
    metadata:
      labels:
        app: argocd-hello
