name: External Webhook Receiver

on:
  repository_dispatch:
    types: [external_webhook]

jobs:
  hello_job:
    runs-on: linux-runner
    steps:
      - name: Print Hello World
        run: echo "Hello World"
