name: External Webhook Receiver

on:
  repository_dispatch:
    types: [sdt_auto_external_webhook]

jobs:
  Workflow_Trigger:
    runs-on: linux-runner
    environment: JIRA_Cloud
    steps:
      - name: Checkout # 
        uses: actions/checkout@v4

      - name: Print full client payload (JSON)
        run: echo '${{ toJson(github.event.client_payload) }}'

      - name: Print individual payload fields
        run: |
          echo "Custom Message: ${{ github.event.client_payload.custom_message }}"
          echo "request_id: ${{ github.event.client_payload.request_id }}"
          echo "app_name: ${{ github.event.client_payload.app_name }}"
          echo "app_version: ${{ github.event.client_payload.app_version }}"
          echo "Summary is: ${{ github.event.client_payload.summary }}"

      - name: Run Python script to process data
        run: |
          python git_action_scripts/yaku_workflow_preparer.py
        env:
          JIRA_SERVER: ${{ vars.JIRA_SERVER }}
          JIRA_USERNAME: ${{ vars.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TEST_EXECUTION_KEY: ${{ github.event.client_payload.issue_key }}
          TEST_EXECUTION_SUMMARY: ${{ github.event.client_payload.summary }}
          APP_NAME: ${{ github.event.client_payload.app_name }}
          APP_VERSION: ${{ github.event.client_payload.app_version }}
          REQUEST_ID: ${{ github.event.client_payload.request_id }}
          YAKU_API_TOKEN: ${{ secrets.YAKU_API_TOKEN }}


      