name: External Webhook Receiver

on:
  repository_dispatch:
    types: [external_webhook]

jobs:
  hello_job:
    runs-on: linux-runner
    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Print full client payload (JSON)
        run: echo '${{ toJson(github.event.client_payload) }}'

      - name: Print individual payload fields
        run: |
          echo "Custom Message: ${{ github.event.client_payload.custom_message }}"
          echo "Issue Key: ${{ github.event.client_payload.issue_key }}"

      - name: Run Python script to process data
        run: python git_action_scripts/run1.py

      