name: External Webhook Receiver

on:
  repository_dispatch:
    types: [external_webhook]
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.JIRA_Cloud }}

jobs:
  hello_job:
    runs-on: linux-runner
    steps:
      - name: Checkout # 
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World"

      - name: Print full client payload (JSON)
        run: echo '${{ toJson(github.event.client_payload) }}'

      - name: Print individual payload fields
        run: |
          echo "Custom Message: ${{ github.event.client_payload.custom_message }}"
          echo "Issue Key: ${{ github.event.client_payload.issue_key }}"

      - name: Run Python script to process data
        run: python git_action_scripts/run1.py
        env:
          JIRA_SERVER: ${{ vars.JIRA_SERVER }}
          JIRA_USERNAME: ${{ vars.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ vars.JIRA_API_TOKEN }}


      